import { FileNode } from './types';

export const WORK_DIRS: FileNode[] = [
  { id: '1', name: 'Project_Alpha_2023_Nov', type: 'folder', path: 'Z:/BioData/2023_11' },
  { id: '2', name: 'River_Samples_eDNA', type: 'folder', path: 'Z:/BioData/River_eDNA' },
  { id: '3', name: 'QIIME2_Test_Run', type: 'folder', path: 'Z:/BioData/Test_Runs' },
  { id: '4', name: 'DeepCOI_Training_Set', type: 'folder', path: 'Z:/BioData/Training' },
];

export const MOCK_ANALYSIS_DATA = [
  { name: 'Oncorhynchus mykiss', value: 4500 },
  { name: 'Salmo trutta', value: 3200 },
  { name: 'Cottus gobio', value: 2100 },
  { name: 'Thymallus thymallus', value: 1500 },
  { name: 'Anguilla anguilla', value: 800 },
  { name: 'Unassigned', value: 300 },
];

export const MOCK_SCRIPT = `#!/bin/bash
# Auto-generated by Bio-Agent
# Target: Ubuntu Muscle Node
source /BioAnalyse/miniconda3/etc/profile.d/conda.sh
conda activate obi3

echo "Starting OBITools3 analysis pipeline..."
echo "Working Directory: /media/dell/eDNA/2023_11"

# Define sample mapping based on pattern analysis
declare -A SAMPLES
SAMPLES=( ["JC1"]="GZ24053819" ["JC2"]="GZ24053820" )

for ID in "\${!SAMPLES[@]}"; do
  FILE_PREFIX="\${SAMPLES[$ID]}"
  echo "[INFO] Processing Sample $ID ($FILE_PREFIX)..."
  
  # Align paired ends
  obi alignpairedend -R \
    /media/dell/eDNA/raw/$FILE_PREFIX_R1.fastq.gz \
    /media/dell/eDNA/raw/$FILE_PREFIX_R2.fastq.gz \
    /media/dell/eDNA/aligned/$ID.obialign
    
  # Filter by score
  obi grep -p "sequence['score_norm'] > 0.8" \
    /media/dell/eDNA/aligned/$ID.obialign \
    /media/dell/eDNA/filtered/$ID.good.obialign
done

echo "[SUCCESS] Batch processing complete."
`;
