"""
BioState Definition
===================
Defines the global state for the Multi-Agent Bioinformatics System.
"""

from typing import TypedDict, List, Optional, Dict, Any, Annotated
from langchain_core.messages import BaseMessage
import operator

def add_messages(left: list, right: list):
    """Append messages to the history"""
    return left + right

class BioState(TypedDict):
    """
    Global state for the Bio-Agent system.
    """
    # Chat history (Annotated for append behavior in LangGraph)
    messages: Annotated[List[BaseMessage], add_messages]
    
    # High-level plan generated by Supervisor
    plan: List[str]
    
    # Current execution step description
    current_step: str
    
    # File Manifest: Tracks files across the workflow
    # Structure: {"SampleID": {"raw_r1": "path", "merged": "path", "clean": "path"}}
    file_manifest: Dict[str, Dict[str, str]]
    
    # Quality Control Metrics
    # Structure: {"SampleID": {"merge_rate": 0.99, "denoised_count": 1200}}
    qc_metrics: Dict[str, Dict[str, float]]
    
    # Error Log
    errors: List[str]
    
    # Routing: Which agent should act next?
    next_agent: Optional[str]
    
    # Context retrieved from RAG
    rag_context: Optional[str]
    
    # Active workspace directory on Ubuntu
    workspace_dir: Optional[str]
    
    # Code generated by workers (temporary)
    generated_code: Optional[str]
    
    # Last execution result (for UI display)
    last_execution_result: Optional[Dict[str, Any]]
    
    # Retry counter for error loop
    retry_count: Optional[int]
    
    # Final answer to present to the user
    final_answer: Optional[str]
